### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 511.7 MB 6.2 kB/s 
     |████████████████████████████████| 1.6 MB 59.1 MB/s 
     |████████████████████████████████| 5.8 MB 54.6 MB/s 
     |████████████████████████████████| 438 kB 71.5 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.

In [2]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [3]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[355, 65, 143, 485], [355, 65, 143, 62], [355, 336, 143, 105], [199, 387, 284, 122, 246], [199, 387, 284, 122, 196], [295, 355, 485, 143, 37], [194, 76, 56, 122]]


### Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [12]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 355  65 143 485]
 [  0   0   0   0 355  65 143  62]
 [  0   0   0   0 355 336 143 105]
 [  0   0   0 199 387 284 122 246]
 [  0   0   0 199 387 284 122 196]
 [  0   0   0 295 355 485 143  37]
 [  0   0   0   0 194  76  56 122]]


In [13]:
## 10 feature dimesnions
dim=10


In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 355,  65, 143, 485], dtype=int32)

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 68ms/step


array([[ 0.03509407, -0.01811152, -0.02553065, -0.04140742,  0.00750493,
         0.02019874,  0.04680446, -0.04408742,  0.03369811, -0.00515174],
       [ 0.03509407, -0.01811152, -0.02553065, -0.04140742,  0.00750493,
         0.02019874,  0.04680446, -0.04408742,  0.03369811, -0.00515174],
       [ 0.03509407, -0.01811152, -0.02553065, -0.04140742,  0.00750493,
         0.02019874,  0.04680446, -0.04408742,  0.03369811, -0.00515174],
       [ 0.03509407, -0.01811152, -0.02553065, -0.04140742,  0.00750493,
         0.02019874,  0.04680446, -0.04408742,  0.03369811, -0.00515174],
       [ 0.02358903, -0.00203627,  0.04935385,  0.04856477, -0.03533889,
        -0.04513602,  0.03028983, -0.04928595, -0.04263688,  0.00856396],
       [-0.02416841,  0.04401085, -0.01319609, -0.0086375 , -0.04525457,
         0.02494292,  0.00308961,  0.04983724,  0.0429744 , -0.01685307],
       [ 0.00754126, -0.02785276, -0.03048681, -0.03718401, -0.04268418,
        -0.02228707, -0.02619806,  0.04285822

In [18]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 28ms/step
[[[ 0.03509407 -0.01811152 -0.02553065 -0.04140742  0.00750493
    0.02019874  0.04680446 -0.04408742  0.03369811 -0.00515174]
  [ 0.03509407 -0.01811152 -0.02553065 -0.04140742  0.00750493
    0.02019874  0.04680446 -0.04408742  0.03369811 -0.00515174]
  [ 0.03509407 -0.01811152 -0.02553065 -0.04140742  0.00750493
    0.02019874  0.04680446 -0.04408742  0.03369811 -0.00515174]
  [ 0.03509407 -0.01811152 -0.02553065 -0.04140742  0.00750493
    0.02019874  0.04680446 -0.04408742  0.03369811 -0.00515174]
  [ 0.02358903 -0.00203627  0.04935385  0.04856477 -0.03533889
   -0.04513602  0.03028983 -0.04928595 -0.04263688  0.00856396]
  [-0.02416841  0.04401085 -0.01319609 -0.0086375  -0.04525457
    0.02494292  0.00308961  0.04983724  0.0429744  -0.01685307]
  [ 0.00754126 -0.02785276 -0.03048681 -0.03718401 -0.04268418
   -0.02228707 -0.02619806  0.04285822  0.00649752 -0.00254145]
  [-0.03035358 -0.03623307 -0.00149966  0.02664036 -0.00458

In [19]:
embedded_docs[0]

array([  0,   0,   0,   0, 355,  65, 143, 485], dtype=int32)

In [20]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 17ms/step
[[ 0.03509407 -0.01811152 -0.02553065 -0.04140742  0.00750493  0.02019874
   0.04680446 -0.04408742  0.03369811 -0.00515174]
 [ 0.03509407 -0.01811152 -0.02553065 -0.04140742  0.00750493  0.02019874
   0.04680446 -0.04408742  0.03369811 -0.00515174]
 [ 0.03509407 -0.01811152 -0.02553065 -0.04140742  0.00750493  0.02019874
   0.04680446 -0.04408742  0.03369811 -0.00515174]
 [ 0.03509407 -0.01811152 -0.02553065 -0.04140742  0.00750493  0.02019874
   0.04680446 -0.04408742  0.03369811 -0.00515174]
 [ 0.02358903 -0.00203627  0.04935385  0.04856477 -0.03533889 -0.04513602
   0.03028983 -0.04928595 -0.04263688  0.00856396]
 [-0.02416841  0.04401085 -0.01319609 -0.0086375  -0.04525457  0.02494292
   0.00308961  0.04983724  0.0429744  -0.01685307]
 [ 0.00754126 -0.02785276 -0.03048681 -0.03718401 -0.04268418 -0.02228707
  -0.02619806  0.04285822  0.00649752 -0.00254145]
 [-0.03035358 -0.03623307 -0.00149966  0.02664036 -0.00458381 -0.01420831

### Assignment

In [22]:


sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [23]:
vocab_size = 500

In [24]:
from tensorflow.keras.preprocessing.text import one_hot

In [27]:
onehot_repr = [one_hot(words,vocab_size) for words in sent]
print(onehot_repr)

[[355, 267, 111, 284, 446, 176], [44, 241, 111, 100, 274, 451], [199, 106, 375, 155], [355, 493, 111, 187, 355, 471], [419, 416, 431, 111, 100, 274, 451], [400, 111, 100, 274, 84, 302]]


In [34]:
sent_len = 8

In [35]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [36]:
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[  0   0 355 267 111 284 446 176]
 [  0   0  44 241 111 100 274 451]
 [  0   0   0   0 199 106 375 155]
 [  0   0 355 493 111 187 355 471]
 [  0 419 416 431 111 100 274 451]
 [  0   0 400 111 100 274  84 302]]


In [37]:
dimn = 10
model = Sequential()
model.add(Embedding(vocab_size,10,input_length = sent_len))
model.compile('adam','mse')

In [38]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [39]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 30ms/step


array([[[ 0.02258198, -0.0301483 ,  0.04729221,  0.02389121,
          0.03563383,  0.00142531, -0.01010094, -0.04068403,
         -0.02186536,  0.04724214],
        [ 0.02258198, -0.0301483 ,  0.04729221,  0.02389121,
          0.03563383,  0.00142531, -0.01010094, -0.04068403,
         -0.02186536,  0.04724214],
        [-0.03796562,  0.02127593, -0.01894348, -0.03594025,
         -0.00923138,  0.0288031 ,  0.00863392, -0.00150547,
          0.03514353,  0.00782015],
        [ 0.01453706,  0.03359247,  0.02253035,  0.03269616,
         -0.00512557,  0.02261117,  0.01329989,  0.01727774,
          0.04286985, -0.00867001],
        [ 0.02213447,  0.00330007, -0.02600918, -0.03170508,
          0.01174644,  0.00297081, -0.02394829,  0.04956242,
         -0.00848875,  0.00052375],
        [-0.01269652,  0.0225412 , -0.0080496 , -0.04450696,
         -0.02824329,  0.02252371, -0.03248848, -0.03150199,
         -0.04989563, -0.03877071],
        [-0.01314201, -0.0213148 ,  0.04365541, -0.0